name: 🛡️ Inspeção de Qualidade (ShellCheck)

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    shellcheck:
        name: Analisar Scripts Bash
        runs-on: ubuntu-latest

        steps:
            - name: 📥 Clonar o Repositório
              uses: actions/checkout@v4

            - name: 🔍 Rodar ShellCheck Nativo
              run: shellcheck *.sh --exclude=SC2086,SC2155,SC2046,SC2002,SC2024,SC2016,SC2015,SC2162
